version: '3.8'

services:
  web:
    build: .
    container_name: webshop
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"